name: tflite_image_classification
description: A new Flutter project.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=2.16.1 <3.0.0"
dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  tflite: ^1.1.2
  image_picker: ^0.8.4+11
  dotted_border: ^2.0.0+3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^1.0.0
  flutter_launcher_icons: "^0.9.2"

flutter:
  uses-material-design: true
  fonts:
    - family: PatrickHand-Regular
      fonts:
        - asset: assets/fonts/PatrickHand-Regular.ttf


  assets:
    - assets/
    - assets/images/
    - assets/CnnModel.tflite
    - assets/labels.txt


